"""Add table report_model_custom_field

Revision ID: 28fbe072523a
Revises: 066134a29f29
Create Date: 2021-03-10 18:12:33.157642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "28fbe072523a"
down_revision = "066134a29f29"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_model_custom_field",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("report_model_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("index", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "string", "boolean", "number", "date", "file", name="fieldtypeenum"
            ),
            nullable=False,
        ),
        sa.Column("enum", sa.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(
            ["report_model_id"],
            ["reports.report_model.id"],
            name=op.f("fk_report_model_custom_field_report_model_id_report_model"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_model_custom_field")),
        sa.UniqueConstraint("report_model_id", "index", name="report_model_index_uc"),
        sa.UniqueConstraint("report_model_id", "name", name="report_model_name_uc"),
        schema="reports",
    )
    op.drop_column("report_model", "custom_field_schema", schema="reports")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "report_model",
        sa.Column(
            "custom_field_schema",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        schema="reports",
    )
    op.drop_table("report_model_custom_field", schema="reports")
    # ### end Alembic commands ###
