#!/bin/bash

# start slapd in background
echo -n "Starting slapd daemon in background..."
slapd -u ${RUN_AS_UID} -g ${RUN_AS_GID} -h "ldapi:/// ldap://127.0.0.1/"
echo "Started: OK"

echo -n "Waiting for LDAP deamon to start..."
while true; do
    sleep 1
    ldapsearch -x >/dev/null 2>&1
    if [ $? -eq 0 ]; then
        break
    fi
done;
echo "Waiting: OK"


ldapadd -D "cn=admin,dc=georchestra,dc=org" -w "$SLAPD_PASSWORD" -H ldap://127.0.0.1:389 -f role_report_admin.ldif

pkill slapd

# wait for ldap to stop
echo -n "Waiting for LDAP to stop..."
while true; do
    sleep 1
    pgrep slapd >/dev/null 2>&1
    if [ $? -ne 0 ]; then
        break
    fi
done;
echo "Waiting: OK"